# -*- coding: utf-8 -*-
"""base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-9qTrY_2fw0CVzahSnraXPApX5wLV-a
"""

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ scoring/base.py — 스코어러 인터페이스                                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# 파일 경로: scoring/base.py

# content-begin: scoring/base.py
from abc import ABC, abstractmethod

class Scorer(ABC):
    @abstractmethod
    def score(self, answers:list, meta:dict) -> dict:
        """return {"total":int, "max":int|None, "domains":{...}}"""
# content-end: scoring/base.py