# -*- coding: utf-8 -*-
"""dhi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-9qTrY_2fw0CVzahSnraXPApX5wLV-a
"""

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ scoring/dhi.py — DHI 채점기                                           ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# 파일 경로: scoring/dhi.py

# content-begin: scoring/dhi.py
from .base import Scorer

class DHIScorer(Scorer):
    def score(self, answers, meta):
        total = sum(a["score"] for a in answers)
        doms = {k:0 for k in meta.get("domains", {}).keys()}
        for a in answers:
            doms[a["domain"]] = doms.get(a["domain"], 0) + a["score"]
        return {"total": total, "max": meta.get("max_score"), "domains": doms}
# content-end: scoring/dhi.py