# -*- coding: utf-8 -*-
"""hit6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jc-gxQtQwRn_g4hp2efMuRocOSDm1-v2
"""

# scoring/hit6.py
from typing import List, Dict, Any

class HIT6Scorer:
    def score(self, answers: List[Dict[str, Any]], meta: Dict[str, Any]) -> Dict[str, Any]:
        total = 0
        for a in answers:
            val = a.get("score", 0)
            try:
                total += int(val)
            except Exception:
                pass
        return {
            "total": total,
            "max": meta.get("max_score", 78),
            "domains": {},
        }