# -*- coding: utf-8 -*-
"""midas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jc-gxQtQwRn_g4hp2efMuRocOSDm1-v2
"""

from typing import List, Dict, Any

class MIDASScorer:
    def score(self, answers: List[Dict[str, Any]], meta: Dict[str, Any]) -> Dict[str, Any]:
        total = 0
        scored_items = 0
        for a in answers:
            # weight=1만 총점 반영, None은 0으로 간주
            weight = 1
            # 해당 문항의 weight를 meta.items에서 찾아 반영
            for it in meta.get("items", []):
                if it.get("no") == a.get("no"):
                    weight = it.get("weight", 1)
                    break
            if weight == 1:
                val = a.get("score")
                if isinstance(val, int):
                    total += max(0, val)
                scored_items += 1
        return {
            "total": total,
            "max": meta.get("max_score", 270),
            "domains": {},   # MIDAS는 도메인 점수 없음
        }