# -*- coding: utf-8 -*-
"""vadl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-9qTrY_2fw0CVzahSnraXPApX5wLV-a
"""

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ scoring/vadl.py — VADL 채점기                                         ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# 파일 경로: scoring/vadl.py

# content-begin: scoring/vadl.py
from .base import Scorer

class VADLScorer(Scorer):
    def score(self, answers, meta):
        nums = [a["score"] for a in answers if isinstance(a.get("score"), (int,float))]
        total = int(sum(nums))
        maxv  = len(nums) * 10
        doms = {k:0 for k in meta.get("domains", {}).keys()}
        for a in answers:
            if isinstance(a.get("score"), (int,float)):
                doms[a["domain"]] = doms.get(a["domain"], 0) + a["score"]
        return {"total": total, "max": maxv, "domains": doms}