# -*- coding: utf-8 -*-
"""consistency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-9qTrY_2fw0CVzahSnraXPApX5wLV-a
"""

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ utils/consistency.py — 규칙 기반 이상탐지(경량)                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# 파일 경로: utils/consistency.py

# content-begin: utils/consistency.py
import json
from pathlib import Path
from typing import Dict, Any, List


def make_payload(per_survey_raw: Dict[str, list], per_survey_summaries: Dict[str, dict]) -> Dict[str, Any]:
    payload = {}

    # DHI
    if "DHI" in per_survey_summaries:
        s = per_survey_summaries["DHI"]
        payload["DHI"] = {
            "total": s.get("total", 0),
            "domains": s.get("domains", {}),
        }

    # VADL
    if "VADL" in per_survey_raw:
        answers = per_survey_raw["VADL"]
        core_ids = {13,14,15,16,17}
        nums = [a["score"] for a in answers if isinstance(a.get("score"), (int, float))]
        core = [a["score"] for a in answers if a["no"] in core_ids and isinstance(a.get("score"), (int,float))]
        payload["VADL"] = {
            "scores": {str(a["no"]): a["score"] for a in answers if a.get("score") is not None},
            "NA": [a["no"] for a in answers if a.get("score") is None],
            "core_any_gte": max(core) if core else None,
            "all_scores_lte": (len(nums)>0 and all(s <= 3 for s in nums)),
            "core_mean": (sum(core)/len(core) if core else None),
        }
    return payload


def load_rulebook(path: Path) -> dict:
    return json.load(open(path, "r", encoding="utf-8"))


def eval_rules(payload: Dict[str, Any], rulebook: dict) -> List[Dict[str, Any]]:
    flags = []
    dhi = payload.get("DHI", {})
    vadl = payload.get("VADL", {})

    for r in rulebook.get("rules", []):
        w = r.get("when", {})
        ok = True
        if "VADL.core_any_gte" in w:
            val = vadl.get("core_any_gte") if vadl else None
            ok &= (val is not None and val >= w["VADL.core_any_gte"])
        if "VADL.all_scores_lte" in w:
            ok &= (vadl.get("all_scores_lte") == w["VADL.all_scores_lte"])
        if "DHI.total_range" in w:
            lo, hi = w["DHI.total_range"]
            t = dhi.get("total", -1)
            ok &= (lo <= t <= hi)
        if "DHI.total_gte" in w:
            t = dhi.get("total", -1)
            ok &= (t >= w["DHI.total_gte"])
        if ok:
            flags.append({
                "id": r["id"],
                "severity": r.get("severity", "low"),
                "reason": r.get("explain", ""),
                "suggestion": r.get("suggest", []),
            })
    return flags
# content-end: utils/consistency.py