# -*- coding: utf-8 -*-
"""export.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-9qTrY_2fw0CVzahSnraXPApX5wLV-a
"""

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ utils/export.py — CSV/Sheets 내보내기                                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# 파일 경로: utils/export.py

# content-begin: utils/export.py
from typing import Dict

try:
    import gspread
except Exception:
    gspread = None

import streamlit as st
import pandas as pd


def build_row(timestamp: str, participant_id: str, preset: str,
              per_survey_summaries: Dict, per_survey_raw: Dict) -> dict:
    row = {
        "timestamp": timestamp,
        "participant_id": participant_id,
        "preset": preset,
        "selected_surveys": ",".join(per_survey_summaries.keys()),
    }
    for k, s in per_survey_summaries.items():
        row[f"{k}_total"] = s.get("total")
        if s.get("max") is not None:
            row[f"{k}_max"] = s.get("max")
        for dk, dv in s.get("domains", {}).items():
            row[f"{k}_sum_{dk}"] = dv
    return row

@st.cache_resource(show_spinner=False)
def _gspread_client_from_secrets():
    if gspread is None:
        return None
    try:
        sa_info = st.secrets.get("gcp_service_account", None)
        if not sa_info:
            return None
        return gspread.service_account_from_dict(sa_info)
    except Exception:
        return None


def save_df_to_gsheet(df: pd.DataFrame, spreadsheet_url: str, worksheet_name: str = "responses"):
    gc = _gspread_client_from_secrets()
    if gc is None:
        raise RuntimeError("gspread 사용 불가 또는 st.secrets['gcp_service_account'] 미설정")
    sh = gc.open_by_url(spreadsheet_url)
    try:
        ws = sh.worksheet(worksheet_name)
    except Exception:
        ws = sh.add_worksheet(title=worksheet_name, rows="1000", cols="50")
    if not ws.acell("A1").value:
        ws.append_row(df.columns.tolist())
    ws.append_row(df.iloc[0].astype(str).tolist())
    return True
# content-end: utils/export.py