# -*- coding: utf-8 -*-
"""registry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-9qTrY_2fw0CVzahSnraXPApX5wLV-a
"""

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ utils/registry.py — 설문 목록/로드 (YAML 분리·지연 로딩)                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# 파일 경로: utils/registry.py

# content-begin: utils/registry.py
"""
설문 레지스트리: surveys/*.yaml 메타 스캔 및 로딩
"""
from pathlib import Path
import yaml

SURVEYS_DIR = Path("surveys")

def list_surveys():
    metas = []
    for p in sorted(SURVEYS_DIR.glob("*.yaml")):
        meta = yaml.safe_load(open(p, "r", encoding="utf-8"))
        metas.append({
            "key": meta["key"],
            "title": meta["title"],
            "input_type": meta.get("input_type", "radio"),
            "domains": meta.get("domains", {}),
        })
    return metas

def load_survey(key: str):
    p = SURVEYS_DIR / f"{key}.yaml"
    meta = yaml.safe_load(open(p, "r", encoding="utf-8"))
    return meta